name: ci

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: npm ci
      - run: npm test

  release:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v4
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
